BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;
TRUNCATE TABLE "role" CASCADE;
TRUNCATE TABLE "product" CASCADE;
TRUNCATE TABLE "image" CASCADE;
TRUNCATE TABLE "product_category" CASCADE;
TRUNCATE TABLE "categories" CASCADE;
TRUNCATE TABLE "order" CASCADE;
TRUNCATE TABLE "product_order" CASCADE;

SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"role"', 'id')), 1, FALSE);
SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"categories"', 'id')), 1, FALSE);


COMMIT;